/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mypkg.secretimagesharingschemeui;

/**
 *
 * @author 14R PC
 */
public class ShamirSecretSharingUI extends javax.swing.JFrame {

    /**
     * Creates new form ShamirSecretSharingUI
     */
    public ShamirSecretSharingUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        sssEncrypt = new javax.swing.JButton();
        sssRcvrHstimg = new javax.swing.JButton();
        sssRcvrWtrmrk = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Menu SSS");

        sssEncrypt.setText("Encrypt Image");
        sssEncrypt.setMaximumSize(new java.awt.Dimension(162, 23));
        sssEncrypt.setMinimumSize(new java.awt.Dimension(162, 23));
        sssEncrypt.setPreferredSize(new java.awt.Dimension(162, 23));
        sssEncrypt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sssEncryptActionPerformed(evt);
            }
        });

        sssRcvrHstimg.setText("Recover Host Image");
        sssRcvrHstimg.setMaximumSize(new java.awt.Dimension(162, 23));
        sssRcvrHstimg.setMinimumSize(new java.awt.Dimension(162, 23));
        sssRcvrHstimg.setPreferredSize(new java.awt.Dimension(162, 23));
        sssRcvrHstimg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sssRcvrHstimgActionPerformed(evt);
            }
        });

        sssRcvrWtrmrk.setText("Recover Watermark Image");
        sssRcvrWtrmrk.setMaximumSize(new java.awt.Dimension(162, 23));
        sssRcvrWtrmrk.setMinimumSize(new java.awt.Dimension(162, 23));
        sssRcvrWtrmrk.setPreferredSize(new java.awt.Dimension(162, 23));
        sssRcvrWtrmrk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sssRcvrWtrmrkActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(119, 119, 119)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(sssRcvrWtrmrk, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sssRcvrHstimg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sssEncrypt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(166, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(165, 165, 165))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(jLabel1)
                .addGap(54, 54, 54)
                .addComponent(sssEncrypt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(sssRcvrHstimg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(sssRcvrWtrmrk, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(74, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void sssRcvrHstimgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sssRcvrHstimgActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sssRcvrHstimgActionPerformed

    private void sssRcvrWtrmrkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sssRcvrWtrmrkActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sssRcvrWtrmrkActionPerformed

    private void sssEncryptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sssEncryptActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sssEncryptActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ShamirSecretSharingUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ShamirSecretSharingUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ShamirSecretSharingUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ShamirSecretSharingUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ShamirSecretSharingUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton sssEncrypt;
    private javax.swing.JButton sssRcvrHstimg;
    private javax.swing.JButton sssRcvrWtrmrk;
    // End of variables declaration//GEN-END:variables
}
